# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:The Scarlet Lo-Lo 
Cooking Show
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "The Scarlet Lo-Lo 
Cooking Show"
![image]([img]https://i.ibb.co/C8VxGVy/Lo-Lo-Logo22.png[/img])
description:	       "a minimalist Jekyll theme for running a blog or publication"
author:              "Paul Le"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
